/*

This script was automagically generated by SQL for Unity Workbench V.1.0.7 (c) Schema version V.1.0.3 Copyright SteveSmith.Software 2018. All Rights Reserved


You may modify this code as you wish. But any changes will be lost if you re-create the database

Should this script fail to compile and run under Unity it is probable that you have used either a C# or Unity reserved word as a column name.

If a Column Name is invalid rename the column in the SQL for Unity Workbench and Create the database again
HINT: Often changing the case or adding a prefix will be enough

If this fails to resolve the problem please report it at https://stevesmith.software
or email SQL4Unity@stevesmith.software

*/
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;
public partial class playerprefsplus_playerprefvalue: SQL4Unity.SQLRow {
public new ushort rowId { get { return Get<ushort>(24); } }
public int PlayerPrefID { get { return Get<int>(26); } set { Set(26, value); } }
public int Seq { get { return Get<int>(27); } set { Set(27, value); } }
public string StringVal { get { return Get<string>(28); } set { Set(28, value); } }
public int IntVal { get { return Get<int>(29); } set { Set(29, value); } }
public bool BoolVal { get { return Get<bool>(30); } set { Set(30, value); } }
public Vector2 V2Val { get { return Get<Vector2>(31); } set { Set(31, value); } }
public Vector3 V3Val { get { return Get<Vector3>(32); } set { Set(32, value); } }
public Vector4 V4Val { get { return Get<Vector4>(33); } set { Set(33, value); } }
public GameObject GoVal { get { return Get<GameObject>(34); } set { Set(34, value); } }
public float FloatVal { get { return Get<float>(35); } set { Set(35, value); } }
public long LongVal { get { return Get<long>(36); } set { Set(36, value); } }
public byte ByteVal { get { return Get<byte>(37); } set { Set(37, value); } }
public SQL4Unity.SQLDate DateVal { get { return Get<SQL4Unity.SQLDate>(38); } set { Set(38, value); } }
public Color ColVal { get { return Get<Color>(39); } set { Set(39, value); } }
public Quaternion QuatVal { get { return Get<Quaternion>(40); } set { Set(40, value); } }
public Rect RectVal { get { return Get<Rect>(41); } set { Set(41, value); } }
public Sprite SpriteVal { get { return Get<Sprite>(42); } set { Set(42, value); } }
public UnityEngine.Object ResVal { get { return Get<UnityEngine.Object>(43); } set { Set(43, value); } }
/// <summary>
/// Depreciated. This method included for legacy reasons only
/// </summary>
public override void Get(Dictionary<string,object> row) {  }
}
